CREATE OR REPLACE TRIGGER tr_alojamiento
BEFORE INSERT ON EMPLEADO
FOR EACH ROW
DECLARE
BEGIN
    IF :NEW.ALOJAMIENTO IS NULL THEN
    END IF;
END;
/

SET AUTOCOMMIT OFF;
INSERT INTO OFICIOEMPLEADO (EMPLEADO, OFICIO) VALUES (11, 4);
SELECT * FROM OFICIOEMPLEADO WHERE EMPLEADO = 11;
ROLLBACK;


SELECT
    A.NOMBRECOMPLETO,
    COUNT(E.NUMEMP) AS "TOTAL DE EMPLEADOS"
FROM
    ALOJAMIENTO A
    JOIN EMPLEADO E
    ON A.NUMALOJ = E.ALOJAMIENTO
GROUP BY
    A.NOMBRECOMPLETO
HAVING COUNT(E.NUMEMP) = (
    SELECT
        MAX(COUNT(E.NUMEMP))
    FROM
        ALOJAMIENTO A
        JOIN EMPLEADO E
        ON A.NUMALOJ = E.ALOJAMIENTO
    GROUP BY
        A.NOMBRECOMPLETO
    FETCH FIRST ROW ONLY
)
ORDER BY
    "TOTAL DE EMPLEADOS" DESC;