DROP TABLE STUDENTS;
DROP TABLE LOG_TABLE;

CREATE TABLE LOG_TABLE
(
  INFO VARCHAR2(30)
);

CREATE TABLE STUDENTS
(
  ID      NUMBER(5)    NOT NULL,
  NAME    VARCHAR2(20),
  SURNAME VARCHAR(20) ,
  CONSTRAINT PK_STUDENTS PRIMARY KEY (ID)
);
