SET SERVEROUTPUT ON;
DECLARE
    V_OFICIO OFICIO%ROWTYPE;
    V_RES BOOLEAN;

    PROCEDURE PRINT( P_RES BOOLEAN, P_OFICIO OFICIO%ROWTYPE ) IS
    BEGIN
        IF P_RES THEN
            DBMS_OUTPUT.PUT_LINE('id=' || P_OFICIO.NUMOFICIO || ' ofi=' || TRIM(P_OFICIO.OFICIO) || ' desc=' || TRIM(P_OFICIO.DESCRIPCION) );
        ELSE
            DBMS_OUTPUT.PUT_LINE('id=' || TRIM(P_OFICIO.NUMOFICIO || ' no existe') );
        END IF;
    END;

    FUNCTION setOficio (v_oficio OFICIO%ROWTYPE) RETURN BOOLEAN IS
        v_numoficio OFICIO.NUMOFICIO%TYPE;
    BEGIN
        SELECT OFICIO.NUMOFICIO INTO v_numoficio FROM OFICIO WHERE NUMOFICIO = v_oficio.NUMOFICIO;
        RETURN TRUE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
    END;

BEGIN
    -- Cambio de nombre del oficio 1 de LEÑADOR a PROFESOR
    SELECT * INTO V_OFICIO FROM OFICIO WHERE NUMOFICIO = 1;
    V_OFICIO.OFICIO := 'PROFESOR';
    -- Devuelve true si lo ha podido encontrar
    V_RES := SETOFICIO(V_OFICIO);
    PRINT (V_RES, V_OFICIO);
    -- Hago trampa y digo que es id 30 (no existe)
    V_OFICIO.NUMOFICIO := 30;
    V_RES := SETOFICIO(V_OFICIO);
    PRINT (V_RES, V_OFICIO);
END;
/
ROLLBACK;