DROP TABLE STUDENTS;
DROP TABLE LOG_TABLE;


CREATE TABLE LOG_TABLE
(
  INFO VARCHAR2(30)
);

CREATE TABLE STUDENTS
(
  ID         NUMBER(5)    NOT NULL,
  FIRST_NAME VARCHAR2(20),
  LAST_NAME  VARCHAR(20) ,
  CONSTRAINT PK_STUDENTS PRIMARY KEY (ID)
);
