DECLARE
  CURSOR C_ALOJAMIENTO IS
  SELECT
    *
  FROM
    ALOJAMIENTO
  ORDER BY
    ALOJAMIENTO;
  CURSOR C_EMPLEADO (
    P_NUMALOJ ALOJAMIENTO.NUMALOJ%TYPE
  ) IS
  SELECT
    *
  FROM
    EMPLEADO
  WHERE
    ALOJAMIENTO=P_NUMALOJ
  ORDER BY
    NOMBRE;
BEGIN
  FOR V_ALOJAMIENTO IN (
    SELECT
      *
    FROM
      ALOJAMIENTO
    ORDER BY
      ALOJAMIENTO
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(V_ALOJAMIENTO.ALOJAMIENTO);
    FOR V_EMPLEADO IN C_EMPLEADO(V_ALOJAMIENTO.NUMALOJ) LOOP
      DBMS_OUTPUT.PUT_LINE(CHR(9)
                           ||V_EMPLEADO.NOMBRE);
    END LOOP;
  END LOOP;
 -- Aquí Hay un close implícito
 -- A priori parece mejor opción pero intenta resolver el ejercicio DetallePedidoAgrupado con FOR
END;
/